apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  labels:
    app: {{ template "kibana.name" . }}
data:
  kibana.yml: |-
    server.name: kibana
    server.host: "0"
    xpack.security.enabled: "true"
    elasticsearch.hosts: "http://elastic:9200"
    elasticsearch.username: "kibana"
    elasticsearch.password: "kibana_password"

