apiVersion: v1
kind: Service
metadata:
  name: {{ template "kibana.fullname" . }}
  labels:
    app: {{ template "kibana.name" . }}
spec:
  ports:
  - port: 5601
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "kibana.name" . }}