apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "filebeat.fullname" . }}
  labels:
    app: {{ template "filebeat.name" . }}
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      exclude_files: 
        - cluster-autoscaler-.*\.log
        - fluentd-cloudwatch-.*\.log
        - metrics-server-.*\.log
        - filebeat-.*\.log
        - kibana-.*\.log
        - elastic-.*\.log
      # multiline.pattern: 'query: {'
      # multiline.negate: true
      # multiline.match: after
        
      processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"

    output.elasticsearch:
      hosts: ["http://elastic:9200"]
      username: "elastic"
      password: "elastic_password"
      


