apiVersion: v1
kind: Service
metadata:
  name: {{ template "elastic.fullname" . }}
  labels:
    app: {{ template "elastic.name" . }}
spec:
  ports:
  - port: 9200
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "elastic.name" . }}