apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "elastic.fullname" . }}
  labels:
    app: {{ template "elastic.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "elastic.name" . }}
  serviceName: {{ template "elastic.name" . }}
  replicas: 2
  template:
    metadata:
      labels:
        app: {{ template "elastic.name" . }}
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ['chown', '-R', '1000:1000', '/usr/share/elasticsearch/data']
        securityContext:
          privileged: true
        volumeMounts:
        - name: {{ template "elastic.fullname" . }}
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true

      containers:
      - name: elastic
        image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
        env:
        - name: cluster.name
          value: eks-cluster
        - name: node.name
          valueFrom: 
            fieldRef:
              fieldPath: metadata.name
        - name: discovery.seed_hosts
          value: elastic-0.elastic,elastic-1.elastic
        - name: cluster.initial_master_nodes
          value: elastic-0,elastic-1
        - name: ES_JAVA_OPTS
          value: "-Xms1300m -Xmx1300m"
        - name: xpack.security.enabled
          value: "true"
        ports:
        - containerPort: 9200
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: {{ template "elastic.fullname" . }}
          mountPath: /usr/share/elasticsearch/data

  volumeClaimTemplates:
  - metadata:
      name: {{ template "elastic.fullname" . }}
      labels:
        app: {{ template "elastic.name" . }}
    spec:
      accessModes:
      - {{ .Values.Persistence.accessMode }}
      resources:
        requests:
          storage: {{ .Values.Persistence.size }}